import Head from "next/head";
import React, { useEffect,useState } from "react";
import OfferBanner from "../Banners/OfferBanner";
import Filters from "../Filters/Filters";
import SubNavbar from "../Navbar/SubNavbar";
import Offers from "../Offers";
import WeekTopOffers from "../WeekTopOffers";
import { useSelector } from "react-redux";
import {  FormattedMessage } from 'react-intl';
import { useRouter } from "next/router";


const FilterLayout = ({ headTitle, children }) => {
 
  
  const isLoggedIn = useSelector((state) => state.auth?.isLoggedIn);
  const router=useRouter();
 

  // useEffect(()=>{
  //   router.replace(router.pathname, router.pathname, { locale: "sa" })
  // },[])
  return (
    <div className="font-segoe pb-10 bg-secondary">
      <Head>
        <title>Prix Offers | {headTitle}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      {isLoggedIn ? (
        <OfferBanner
          title={<FormattedMessage id="OfferBannerTile" /> }
          description={<FormattedMessage id="OfferBannerDescription" /> }
          hidden
        />
      ) : (
        <OfferBanner
        title={<FormattedMessage id="OfferBannerTile" /> }
        description={<FormattedMessage id="OfferBannerDescription" /> }
        />
      )}
      <div className="flex justify-center bg-secondary mb">
        <div className="grid grid-cols-5 gap-5 pt-2 p-0 sm:p-5 max-w-7xl">
          <Filters />
          <div className="bg-transparent w-full h-30 col-span-5 lg:col-span-4 px-3">
          <SubNavbar />
            
           
            <WeekTopOffers headTitle={headTitle}/>
            {children}
          </div>
        </div>
      </div>
    </div>
   
  );
};

export default FilterLayout;
